### PR TITLE
Add new hook for override RSS tags

### PR DESCRIPTION
**Pull request by Roffun**
I propose to add a hook rss.items_row to be able to override its
function or process tags RSS

### CODE REVIEW

**Comment by Alex300** [comment]
Hook name must be same as other hook names. Something like 'rss.item.loop'

**Comment by Roffun** [comment]
Macik, I read about the fact that it is desirable to make the function call cot_getextplugins () from the cycle to accelerate the execution of the script. But specifically in this case, the hook is needed before $t->parse('MAIN.ITEM_ROW');

Alex300, I changed the name of the hook on your proposed то https://github.com/Cotonti/Cotonti/pull/1556/files.

**Comment by Alex300** [comment]
If you need hook in the cicle, you must get a files list to include outside from it.

```php
/* === Hook - Part1 : Set === */
// Get file list for include
$extp = cot_getextplugins('myext.some.loop');
/* ===== */
 
// Our cicle
foreach ($items as $item)
{
    // Some code here...
 
    /* === Hook - Part2 : Include === */
    // Fire the hook
    foreach ($extp as $pl)
    {
        // Include all files from the list above
        include $pl;
    }
    /* ===== */
 
    $t->parse('MAIN.ITEM_ROW');
}
```

**Comment by Roffun** [comment]
thank you for the example, but the solution has already been found without the need for additional hooks. I made a function of the global, and now turned out to redefine the existing tags via rss.output

**Pull request closed without merging**
